google/ctfscoreboard

config.py
scoreboard/config_defaults.py
scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/utils.py

Adds a config option to enable submitting of flags after competition end, with a 0 point award for doing so.
Does not update UI, still shows the same "Game Over" message regardless.

Allow for the submitting of flags after game end

---

scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/base.py

[resolves #6] changed flask.ext.* to flask_* to resolve deprecation warnings

Upgraded flask namespacing

---

scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/data.py
scoreboard/utils.py
static/js/controllers/admin/challenges.js
static/js/controllers/challenges.js
static/partials/admin/challenge.html

Give UUIDs to Challenge, Hint, and Category fields

---

scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/data.py

[Resolves #10] Adds rest endpoints for creation, deletion, and modification, as well as model support for storing tags in a many-to-many relationship with challenges.

Add Backend Tag Support

---

static/css/scoreboard.css

Added perspective to flipping challenges

---

README.md
scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/data.py
static/js/controllers/admin/challenges.js
static/js/directives.js
static/partials/admin/challenge.html
static/partials/challenges.html
static/partials/components/challenge.html

Removes support for hints as discussed.

Remove support for hints.  (Issue #23)

---

README.md

Modify README.md about configurations people may need.

Modify README>

---

scoreboard/logger.py

fixed bug when uid was unset in flask.g

---

scoreboard/tests/base.py
scoreboard/tests/rest_test.py

Also creates a basic test.
See issue #32.

Adds a real test harness and basic REST test.

---

static/js/controllers/challenges.js
static/js/directives.js
static/partials/challenge_grid.html
static/scss/scoreboard.scss
templates/base.html

[Resolves #22] Colors are placeholder, however functionality is complete.

Add tag filtering to challenge page

---

static/partials/challenge_grid.html
static/scss/scoreboard.scss

Gives more context as to what tag filtering is

Added tooltip for challenge tags

---

static/js/controllers/page.js
static/partials/page.html

[Resolves #66] I originally made this server-side, but that seemed like unnecessary work for the server, since it had to differentiate between a request made to view a page, and a request made to edit one, which it currently was not doing. This will get more flushed out probably when I address #65

Rudimentary notification that a page can be created

---

scoreboard/attachments/__init__.py
scoreboard/attachments/testing.py
scoreboard/main.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/base.py
scoreboard/tests/rest_test.py
scoreboard/views.py

Since the whole attachments pull request is so big, I went ahead and broke it into two parts, server and client. Here is the first part, which is all of the backend requirements. As of yet, this does not contain any additional testing, however it does pass all of the existing tests. Will update with testing once I determine the best way to include them.

Attachments server

---

static/js/app.js
static/js/controllers/admin/challenges.js
static/js/services/challenges.js
static/js/services/upload.js
static/partials/admin/attachments.html
static/partials/admin/challenge.html
static/scss/scoreboard.scss
templates/base.html

This is the sister commit of #62 and also addresses #11

Add front end support for many to many attachments

---

scoreboard/rest.py
static/js/app.js
static/js/controllers/admin/challenges.js
static/js/services/page.js
static/partials/admin/pages.html
static/scss/scoreboard.scss
templates/base.html

UI allows for listing pages, deleting them, updating their path, editing them, and viewing them. It also has an interface for adding new pages.

Added admin UI for managing pages

---

scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/base.py
scoreboard/tests/rest_test.py

(Working on issue #32.)
This still doesn't cover all the APIs, but because of found bugs that I've fixed as I go, and to prevent diverging too much, I'd like to go ahead and merge.

Add a bunch more rest tests as well as fix some bugs uncovered in testing.

---

scoreboard/controllers.py
scoreboard/rest.py
scoreboard/tests/rest_test.py
scoreboard/utils.py
static/js/controllers/registration.js
static/js/services/global.js
static/js/services/teams.js
static/partials/profile.html
static/scss/scoreboard.scss

Adds an extra option to the profile interface, as well as backend support for switching teams.

Allow users to change teams before the game begins

---

scoreboard/config_defaults.py
scoreboard/context.py
scoreboard/models.py
scoreboard/utils.py

Not a perfect solution, as cookies are left for a while, but better than nothing?  Also, models.Team.current() will *always* return the current one for the user rather than any outdated cookie value.
See issue #76.

Expire idle sessions.

---

scoreboard/context.py

Needs to see if session expires exists

---

scoreboard/tests/rest_test.py

ChangeTeam tests were environment dependent before. Fixed now

Patch time to not rely on config

---

scoreboard/main.py

Addresses bug introduced in #78 wherein the config file is never loaded into the app

Fixed config file loading

---

static/js/services/challenges.js

[Resolves #86] Another one line patch, this time fixing updating and deleting of categories

Fixed reference name from cid to slug

---

static/js/controllers/admin/challenges.js

[Resolves #91] Needed to explicitly update attachment list

Fixed bug where attachments didn't load on challenge creation

---

scoreboard/wsgi.py
static/js/controllers/admin/challenges.js

Resolves bug in the order of module loading

Attachment patch

---

scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/rest_test.py
scoreboard/validators/__init__.py
scoreboard/validators/base.py
scoreboard/validators/per_team.py
scoreboard/validators/static_pbkdf2.py
static/js/controllers/admin/challenges.js
static/partials/admin/challenge.html

We can now validate with per-team flags as well as the standard static flag.
Remaining: page to generate & display flags.

Add pluggable validators

---

main.py
scoreboard/attachments/__init__.py
scoreboard/attachments/file.py
scoreboard/attachments/gcs.py
scoreboard/attachments/testing.py
scoreboard/auth/appengine.py
scoreboard/auth/local.py
scoreboard/cache.py
scoreboard/context.py
scoreboard/controllers.py
scoreboard/logger.py
scoreboard/mail.py
scoreboard/main.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/utils.py
scoreboard/wsgi.py

Applying some pep8 cleanup to the code for more consistent & readable source.

Clean up pep8.

---

main.py
scoreboard/tests/base.py

Tests would fail, but overall result would succeed because the python process did not exit with a non-zero status.

Fix tests.

---

scoreboard/controllers.py
scoreboard/rest.py
scoreboard/validators/nonce.py
scoreboard/validators/per_team.py
static/js/directives.js
static/js/services/challenges.js
static/partials/components/challenge.html

Admins can test that flags are correct.

Allow admins to validate flags

---

scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/rest_test.py
scoreboard/validators/__init__.py
static/js/controllers/admin/teams.js
static/partials/admin/categories.html
static/partials/admin/challenge.html
static/partials/admin/teams.html
static/partials/team.html
static/scss/scoreboard.scss

Admins can grant teams flags -- use with care, it can't be undone!

Allow Admins to Grant Flags

---

config.py
scoreboard/config_defaults.py
scoreboard/controllers.py
scoreboard/rest.py
scoreboard/tests/base.py
scoreboard/tests/rest_test.py
scoreboard/tests/utils_test.py
scoreboard/utils.py
static/js/directives.js
static/js/services/global.js

This provides an option to provide a proof of work on flag submission.  The difficulty of finding a matching key is proportional to 2**PROOF_OF_WORK_BITS.  Values around ~12 provide a few seconds delay per operation (implemented in javascript, using the WebCrypto API).
If you don't want to use this, just set the PROOF_OF_WORK_BITS value to 0, which disables it completely.  (Also is the default value.)
This implements #133.

Proof of Work for Flag Submission

---

scoreboard/rest.py
static/js/controllers/admin/tools.js
static/js/services/admin.js
static/js/services/global.js
static/partials/admin/tools.html

This adds support for performing partial resets:
1. Resetting all scores to 0.
2. Deleting all players & teams.  (Leaves admins unscathed.)
Fixes #136, #128

Reset players or scores.

---

scoreboard/controllers.py
scoreboard/mail.py

This should fix mail sending when properly configured.
Fixes #127.

Improve mail sending.

---

scoreboard/tests/validators_test.py
scoreboard/validators/__init__.py
scoreboard/validators/regex.py

Regex validator.

---

.travis.yml
doc/developing/README.md
doc/developing/requirements.txt
requirements.txt

The beginnings of #169, but something is better than nothing!

Make very basic dev documentation.

---

main.py
scoreboard/cache.py
scoreboard/rest.py
scoreboard/tests/base.py
scoreboard/tests/cache_test.py

Also introduces caching of pages in memcache.

Tests for cache code

---

static/partials/admin/news.html

Remove duplicate attribute.

---

templates/base.html

Fixes rendering issues between 768 and 992 px.  Fixes #218.

Fix left-sided bar on "small" displays.

---

main.py

This uses ipython or the local python shell to launch an interactive
shell to debug issues.
Fixes #226.

Add ability to launch a shell.

---

scoreboard/models.py
scoreboard/rest.py

FIxes #222 without adding any additional queries or latency.
Uses joinedloads to load everything all at once.

Fix display of solve counts and recent solves.

---

.gitignore
.hooks/pre-commit.sh
.travis.yml
doc/developing/requirements.txt
requirements.txt
scoreboard/attachments/__init__.py
scoreboard/attachments/file.py
scoreboard/attachments/testing.py
scoreboard/cache.py
scoreboard/context.py
scoreboard/csrfutil.py
scoreboard/main.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/base.py
scoreboard/tests/csrfutil_test.py
scoreboard/tests/data.py
scoreboard/tests/rest_test.py
scoreboard/utils.py
scoreboard/validators/__init__.py
scoreboard/validators/nonce.py
scoreboard/validators/static_pbkdf2.py

Fixes #63.  In theory.
Currently, tests pass, but haven't really played with it yet.  This is a preview.

Python 3 Support

---

scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/rest_test.py
static/js/controllers/challenges.js
templates/base.html

Fixes #236.  Note that challenges with dependencies are not shown anonymously.

Make challenges visible anonymously.

---

static/partials/challenge_grid.html
static/scss/scoreboard.scss

Make solved challenges more obvious.

---

static/partials/profile.html

Hide team invite link for admins.

---

static/partials/admin/challenge.html
static/scss/scoreboard.scss

Improve UX on admin tag list.

---

scoreboard/context.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/models_test.py
scoreboard/tests/rest_test.py
static/js/controllers/admin/tools.js
static/js/controllers/registration.js
static/js/services/users.js
static/partials/admin/tools.html
static/partials/profile.html

There's currently no UI for viewing the API key, nor an admin interface for bulk revocation, so this is *not* ready to merge.  It's only a preview of the implementation.

Add API Key Support

---

scoreboard/controllers.py
scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/rest_test.py

This creates a new calculation for progressive scoring,

Fix progressive scoring.

---

Dockerfile

This should fix #272 and #148.

Fix building Dockerfile.

---

scoreboard/models.py
scoreboard/rest.py
scoreboard/tests/rest_test.py
static/js/services/challenges.js
static/partials/admin/challenge.html

Fixes various progressive scoring bugs.

Add UI/calculation fixes for Progressive Scoring
